### ISSUE TITLE
Endless installation

### ISSUE THREAD

**Issue by ArtemChandragupta** [Lyndeno/apple-fonts.nix#10]
Hi. 
I added 
`apple-fonts.url = "github:Lyndeno/apple-fonts.nix";`
in my flake.nix
and in my config.nix there is
```
fonts.packages = with pkgs; [
  font-awesome
  iosevka
  material-design-icons
  nerdfonts
  open-sans
  inputs.apple-fonts.packages.${pkg.system}.sf-pro-nerd
];
```
After rebuild I get endless messages (mentioned glyphs are the same in every circle) like this:

![swappy-20240705_181157](https://github.com/Lyndeno/apple-fonts.nix/assets/90765302/2a389710-9164-43ff-b8b2-23f1bf8f17c2)

Also there are multiple nerd font patchers running.
![swappy-20240705_181722](https://github.com/Lyndeno/apple-fonts.nix/assets/90765302/542b2bb7-bed0-4932-8b43-09c087b15a5a)

What have I done wrong?

**Comment by Lyndeno** [comment]
There is nothing wrong, installation does take a while.

Once this initial build is done, you should not have to wait for it on the next builds, unless this flake is updated.
